In [7]:
#Buatlah sebuah fungsi untuk membuat matrix berdasarkan input dari user
import numpy as np

def create_matrix(baris,kolom):
    matrix = [[0 for j in range (kolom)]for i in range (baris)]
    for i in range(baris):
        for j in range(kolom):
            matrix[i][j] =int(input(f"Masukkan elemen untuk [{i+1}][{j+1}] : "))
    view_matrix = np.array(matrix)
    return view_matrix

print(create_matrix(baris = int(input('Masukkan Jumlah Baris:\t')), kolom = int(input('Masukkan Jumlah Kolom:\t'))))


[[2 1 2]
 [3 2 1]
 [4 3 2]]


In [11]:
#Buatlah sebuah fungsi untuk mencari determinan matrix berdasarkan input matrix dari user
import numpy as np

def determinan():
    baris = int(input('Masukkan baris untuk membuat matrix: '))
    kolom = int(input('Masukkan kolom untuk membuat matrix: '))
    if baris == 2 and kolom == 2:
        det = []
        matrix = [[0 for j in range (kolom)]for i in range (baris)]
        for i in range(baris):
            for j in range(kolom):
                matrix[i][j] =int(input(f"Masukkan elemen untuk [{i+1}][{j+1}] : "))
        view_matrix = np.array(matrix)
        print(f'Matrix: \n{view_matrix}')
        hitung_determinan = (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])
        det.append(hitung_determinan)
        int_det = det[0]
    elif baris == 3 and kolom == 3:
        det = []
        matrix = [[0 for j in range (kolom)]for i in range (baris)]
        for i in range(baris):
            for j in range(kolom):
                matrix[i][j] =int(input(f"Masukkan elemen untuk [{i+1}][{j+1}] : "))
        view_matrix = np.array(matrix)
        print(f'Matrix: \n{view_matrix}')
        hitung_determinan = (matrix[0][0] * matrix[1][1] * matrix[2][2]) + (matrix[0][1] * matrix[1][2] * matrix[2][0]) + (matrix[0][2] * matrix[1][0] * matrix[2][1]) - (matrix[0][2] * matrix[1][1] * matrix[2][0]) - (matrix[0][1] * matrix[1][0] * matrix[2][2]) - (matrix[0][0] * matrix[1][2] * matrix[2][1])
        det.append(hitung_determinan)
        int_det = det[0]
    else:
        print('Maaf program ini hanya bisa untuk matrix 2x2 dan matrix 3x3')

    return int_det
print('Determinan dari matrix tersebut adalah', determinan())

Matrix: 
[[5 4]
 [3 4]]
Determinan dari matrix tersebut adalah 8


In [5]:
#Buatlah fungsi untuk mengakalikan dua buah matrix berdasarkan input user menggunakan nested loop
def create_matrix1(row1, column1):
    global matrix1
    matrix1 = [[0 for j in range(column1)]for i in range(row1)]
    for i in range(row1):
        for j in range(column1):
            matrix1[i][j] = int(input(f"Masukkan elemen baris ke-{i+1} dan kolom ke-{j+1}: "))
    return matrix1

row1 = int(input("Masukkan jumlah baris matriks 1 :"))
column1 = int(input("Masukkan jumlah kolom matriks 1 :"))
create_matrix1(row1, column1)

def create_matrix2(row2, column2):
    global matrix2
    matrix2 = [[0 for j in range(column2)]for i in range(row2)]
    for i in range(row2):
        for j in range(column2):
            matrix1[i][j] = int(input(f"Masukkan elemen baris ke-{i+1} dan kolom ke-{j+1}: "))
    return matrix2

row2 = int(input("Masukkan jumlah baris matriks 2 :"))
column2 = int(input("Masukkan jumlah kolom matriks 2 :"))
create_matrix2(row2, column2)

def multiply_maxtrix(matrix1,matrix2):
    m = len(matrix1)
    n = len(matrix2[0])
    p = len(matrix2)


    result = [[0 for j in range(n)] for i in range (m)]
    for i in range (m):
        for j in range(n):
            for k in range (p):
                result [i][j] += matrix1[i][k] * matrix2[k][j]

    for r in result:
        print(r)
        
print("matrik1 = ", matrix1)
print("matrik2 = ", matrix2)
multiply_maxtrix(matrix1,matrix2)

                



matrik1 =  [[5, 6], [7, 8]]
matrik2 =  [[0, 0], [0, 0]]
[0, 0]
[0, 0]
